<html>
<head>
    <meta charset="UTF-8">
    <!--etiqueta importante hace que links de este documento direccionen a partir de la raiz del sitio, por ejemplo: <a href:'home'></a> direcciona al home gracias a esta etiqueta-->
    <base href="<?= BASE_URL ?>">   
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- IMPORT DE BOOTSTRAP -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="./css/style.css">
    <title>Login / FootballData ⚽</title>
</head>
<body>

<div class='vh-100  d-flex justify-content-evenly align-items-center flex-column'>
<h5><a href='<?=BASE_URL?>'>↩Regresar a inicio</a></h5>
<form action='auth' method='POST' class='w-50 h-75 px-5 d-flex flex-column justify-content-center align-items-center border position-relative' >
    <h4 class='position-absolute top-0 mt-5' >Iniciar sesion</h4>
    <div class='w-75 d-flex flex-column justify-content-center align-items-center'>
        <div class="mb-3 w-75">
            <label for="exampleInputEmail1" class="form-label">Nombre de usuario</label>
            <input required type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" max=40 name="userName" placeholder='Usuario' >
        </div>
        <div class="mb-3 w-75">
            <label for="exampleInputPassword1" class="form-label">Contraeña</label>
            <input type="password" class="form-control" id="exampleInputPassword1" max=70 name='password' placeholder='Contraseña'>
        </div>
        <?php if ($errorForm) : ?>
            <div class='alert alert-danger' role='alert'>
                <?= $error ?>
            </div> 
        <?php endif ?>
        <button type="submit" class="btn btn-primary">Iniciar sesion</button>
    </div>
  
    
   
</form>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
</body>
</html>