<html>
<head>
    <meta charset="UTF-8">
    <!--etiqueta importante hace que links de este documento direccionen a partir de la raiz del sitio, por ejemplo: <a href:'home'></a> direcciona al home gracias a esta etiqueta-->
    <base href="<?= BASE_URL ?>">   
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- IMPORT DE BOOTSTRAP -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="<?= BASE_URL ?>/css/style.css">
    <!-- FUNCIONALIDAD TITULO DINAMICO -->
    <title><?= $title;?> / FootballData ⚽</title>
</head>
<body>
  <header>
        <nav class="navbar bg-dark navbar-expand-lg" data-bs-theme="dark">
      
        <div class="container-fluid d-flex justify-content-between w-100">
          <div class='w-50' >
              <h1><a href='<?= BASE_URL ?>'>Data⚽Football</a></h1>
          </div>
          
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse w-15" id="navbarNavDropdown">
          
            <ul class="navbar-nav w-100 d-flex justify-content-end align-items-center">
                <li class='mx-4' ><a href='<?= BASE_URL ?>' >Inicio</a></li>
                <?php foreach ($params as $key => $value ): ?>
                   <li class='mx-4'><a href="<?= $key ?>"><?= $key?><a></li>
                <?php endforeach ?>

                <?php AuthHelper::init(); ?>
                <?php if (!isset($_SESSION['USER_ID'])) : ?>
                    <li>
                      <a href="login">Iniciar sesion</a>
                    </li>
                <?php else : ?>
                  <div class="dropdown">
                      <a class="btn btn-outline-light dropdown-toggle" role='button'  data-bs-toggle="dropdown" aria-expanded="false">
                          <?= $_SESSION['USER_NAME']?>
                      </a>
                      <ul class="dropdown-menu desplegable">
                        <?php foreach ($params as $key => $value ): ?>
                          <li ><a class="dropdown-item" href="admin/<?= $key ?>">⚙ Configuracion <?= $key?><a></li>
                        <?php endforeach ?>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" aria-current="page" href="logout">🔐 Cerrar sesion</a></li>
                      </ul>
                    </div>                    
                  <?php endif ?>    
                                  
            </ul>
              <!-- <form class="d-flex" role="search">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                  </form> --> 
          </div>
        </div>
      </nav>





  
              

      </div>
    </nav>
      

  </header>
  
    